name: Test
on: push

jobs:
  build:
    name: test branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # https://github.com/actions/checkout
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          java-package: jdk
      - run: chmod +x gradlew
      - run: ./gradlew test --info --stacktrace
